### ISSUE TITLE
[idea] Add commands for github CLI

### ISSUE THREAD

**Issue by huylee99** [nguyenanhhoang97/zsh-ahng-g#1]
It would be nice if we have some functions that receive some arguments to replace this bunch of flags (e.g the first four options in the image)

![image](https://user-images.githubusercontent.com/65520688/182002384-e107d955-6784-4658-b095-2e022747497c.png)

**Comment by nguyenanhhoang97** [comment]
Hi @huylee99 , I totally agree with you. We will provide some flag to give user more options for a command. Thank you!
